== Abstraction par langage

* En java
* En python

=== Abstraction en java

[.left-column]
--
[.center]
Interface


[.big]
[source,java,attributes]
----
interface Door {

    void open();

    void close();

    boolean isOpened();
}
----
--

[.right-column]
--
[.center]
Classe abstraite

[.big]
[source,java,attributes]
----
abstract class AbstractDoor {

    private boolean status;

    protected abstract boolean doOpen();
    protected abstract boolean doClose();

    void open(){
        status = doOpen();
    }

    void close(){
        status = ! doClose();
    }

    boolean isOpened() {
        return status;
    }
}
----
--


=== Abstraction en java

[.left-column]
--
[.center]
Classe abstraite

[.big]
[source,java,attributes]
----
abstract class AbstractDoor {
    //...

    protected abstract boolean doOpen();

    protected abstract boolean doClose();

    //...
}
----
--

[.right-column]
--
[.center]
Concrétisation par _extension_

[.big]
[source,java]
----
class DrawbridgeDoor extends AbstractDoor {

    private Drawbridge bridge = new Drawbridge();

    protected boolean doOpen(){
        this.bridge.lift(true);
        return this.bridge.isLifted();
    }

    protected boolean doClose() {
        this.bridge.lift(false);
        return ! this.bridge.isLifted();
    }
}
----
--

=== Abstraction en java


ou utilisation de l'interface `Door`

[.left-column]
--
[.center]
Concrétisation par _implémentation_

[.big]
[source,java]
----
class DrawbridgeDoor implements Door {
    private Drawbridge bridge = new Drawbridge();

    void open(){
        this.bridge.lift(true);
    }
    void close(){
        this.bridge.lift(false);
    }
    boolean isOpened() {
        return this.buld.isLifted();
    }    
}
----
--

[.right-column]
--
[.center]
ou un mix des deux

[.big]
[source,java,attributes]
----
abstract class AbstractDoor implements Door{
    ...
}
class DrawbridgeDoor extends AbstractDoor {
    ...
}
----
--

== Abstraction en Python

* Langage de gentlemen
** Presque tout est accessible 
** Pas de mécanisme de typage fort, 
** Pas de vérification à l'exécution
* Validation laissée à des outils *tiers*
** `Mypy`, `Pytype`, `Pyright/Pylance`
* Abstractions
** Duck walking
** Abstract Base Classes
** Protocol

[NOTE.notes]
--
Le python est un langage de gentlemen, qui se comportent comme il se doit.
Aussi Python n'a pas les mécanismes de Java, comme un typage fort et statique.
Le python ne vérifie jamais le type d'une entitée, il se contente d'utiliser les méthodes qui sont attendues.

Il n'y a pas de mot-clef interface comme en _java_ !

La principale abstraction en Python, c'est le Duck Walking
--


=== Abstraction en Python : Duck Walking

* Duck Walking
** Principale abstraction

[.center]
[quote]
____
Si ça ressemble à un canard, {cr}
si ça nage comme un canard {cr}
et si ça cancane comme un canard, {cr}
c'est un canard
____


=== Abstraction en Python : Duck Walking

[.left-column]
--
[.center]
Type _Porte_

[.big]
[source,python]
----
class Door:
  def open(self):
    ...
  def close(self):
    ...
  def lock(self):
    ...
----
--

[.right-column]
--
[.center]
Type _Four_
[.big]
[source,python]
----
class Oven:
  def open(self):
    ...
  def close(self):
    ...
  def heat(self, temperature):
    ...
----
--

[.reset-column]
--
[.center]
Fonction conçue pour une _Porte_

[.big]
[source,python]
----
def open_and_close(door: Door):
    door.open() # <--- Si ça ouvre comme une porte
    door.close() # <--- Si ça ferme comme une porte
----
--

[%step]
[left-column]
--
[.center]
Fonctionne avec une _Porte_
[.big]
[source,python]
----
door = Door()
open_and_close(door)
----
--

[%step]
[.right-column]
--
[.center]
Fonctionne avec un _Four_

[.big]
[source,python]
----
oven = Oven()
open_and_close(oven)
----
--

=== !

Alors qu'en java

[.big]
[source,java,attributes]
----
class Operator {
    void openAndClose(Door door) { ... }
}

operator.openAndClose(new Door()) // OK

operator.openAndClose(new Oven()) // KO ne compile pas
----

=== Abstraction en Python : Abstract Base Classes

* Module abc - Abstract Base Classes
** Vérifie que des méthode abstraites sont redéfinies à l'instanciation

[.left-column]
--
[.center]
Classe _abstraite_
[.big]
[source,python]
----
from abc import ABC, abstractmethod

class Door(ABC):
    def open(self):
        ...
    def close(self):
        ...    
    @abstractmethod
    def lock(self):
        ...
----
--

[.right-column]
--
[.center]
Classe _dérivée_
[.big]
[source,python]
----
class Oven(Door):
    ... # <-- pas de redéfinitions de @abstractmethod lock
----
--

[%step]
[.reset-column]
--
[.center]
Instanciation
[.big]
[source,python]
----
oven = Oven()
----
[.center]
Erreur au runtime
[.big]
[source]
----
TypeError: Can't instantiate abstract class Oven with abstract method lock
----
--

=== Abstraction en Python : Protocol

[.left-column]
--
[.center]
Définition d'un _protocole_
[.big]
[source,python]
----
from typing import Protocol

class Openable(Protocol):
    def open(self): ...
    def close(self): ...
----
--

[.right-column]
--
[.center]
Définition d'un type attendu
[.big]
[source,python]
----
def open_and_close(openable: Openable):
    openable.open() # <--- Expected

    do_something()
    
    openable.close() # <--- Expected
----
--

[%step]
[.reset-column]
--
[.center]
Toujours pas vérifié au runtime
[.big]
[source,python]
----
class Letter:
    def open(self): ...

open_and_close(Letter()) # <-- Python n'y voit que du feu
----
[source]
----
...
  File "demo.py", line 11, in open_and_close
    openable.close()  # <--- Expected
AttributeError: 'Letter' object has no attribute 'close'
----
--

[%step]
--
[.center]
Mais vérifiable _en amont_ par des outils tiers
[source,bash,attributes]
----
$> mypy .
demo.py:16: error: Argument 1 to "open_and_close" has incompatible type "Letter"; expected "Openable"  [arg-type]
demo.py:16: note: "Letter" is missing following "Openable" protocol member:
demo.py:16: note:     close
----
--