= IDE

// tag::content[]

== Use an IDE

**Use a real editor**

* The best editor is the one you master, but...
. It takes time to **really** master it.
. It may not be the most suitable

ifdef::mode_slide[]
== Use an IDE
endif::[]

[%step]
--
**Go beyond the simple text editor**

____
"I know a guy who can develop with a simple text editor !" +
"I know someone who calculates logarithms in his head." +
"It's possible, but there are more efficient ways."
____
--

== Requirements for IDE

* **Refactoring**
** Renaming (variable, function, method, class, package, ...)
** Signature change (parameter, name and order)
** Move (function, method, class, package, ...)
* **Language-oriented assistant**
** Syntax Highlight and Auto-completion
** Permanent code analysis ( _linter_ )
* **Easy visual debugging** 
** Step-by-step
** With value exploration and modification
* **Navigation**
** Display structure (Outline)
** Fast jump to definition, declaration, etc.

== IDE with refactoring capabilities

* See https://en.wikipedia.org/wiki/Code_refactoring#Automated_code_refactoring

For Python

[.very-packed]
|===
|Language |Editor 

|Python
|VSCode

|Python
|PyCharm

|Java
|Eclipse

|Java
|IntelliJ

|===


[NOTE.notes]
--
Opinionated recommandations

As a Swiss Army Knife: VScode is an everyday nice tool and may be sufficient for a lot a tasks. The plugin system is very clever and can adapt it to every situation. The capabilities to work on https://code.visualstudio.com/docs/remote/ssh[remote server through SSH] is very precious for HPC code, ever if it's not a recommended way of refactoring code. 
Other editors are more language dedicated.
Its Python refactoring capabilities are nevertheless weak. JetBrain products are a lot more powerful but also heavy to use.
For Java both of them, VSCode and IntelliJ are very good. Personally I'm still using Eclipse because I know it pretty well.
--

=== Show Screenshots

* Pycharm
* VSCode


Pycharm refactoring feature are very powerfull



// end::content[]
