= Introduction

// tag::content[]


== Content

* Agility
** Includes expertise
** Includes design
** Includes accept changes

[NOTE.notes]
--
L'agilité est construite autour de 4 valeurs et 12 principes


**Valeurs**

* Valoriser ... plus que ...
** *Les individus et leurs interactions* plus que les processus et les outils,
** *Un logiciel qui fonctionne* plus qu’une documentation exhaustive,
** *La collaboration avec les clients* plus que la négociation contractuelle,
** *L’adaptation au changement* plus que le suivi d’un plan,

**Principes** 

* Plus haute priorité est de satisfaire le client en livrant rapidement et régulièrement des fonctionnalités à grande valeur ajoutée.
* Accueillez positivement les changements de besoins, même tard dans le projet.
* Livrez fréquemment un logiciel opérationnel avec des cycles de quelques semaines à quelques mois et une préférence pour les plus courts.
* Les utilisateurs ou leurs représentants et les développeurs doivent travailler ensemble _quotidiennement_ tout au long du projet.
* Réalisez les projets avec des personnes motivées. Fournissez-leur l’environnement et le soutien dont elles ont besoin et _faites-leur confiance_ pour atteindre les objectifs fixés.
* Privilégiez la co-location de toutes les personnes travaillant ensemble et le dialogue en face à face comme méthode de communication.
* Un logiciel _opérationnel_ est la principale mesure de progression d'un projet.
* Les processus agiles encouragent un rythme de développement _soutenable_. Ensemble, les commanditaires, les développeurs et les utilisateurs devraient être capables de maintenir indéfiniment un rythme constant.
* Une attention continue à l'excellence technique et à un bon design.
* La simplicité – c’est-à-dire l’art de minimiser la quantité de travail inutile – est essentielle.
* Les meilleures architectures, spécifications et conceptions émergent d'équipes auto-organisées.
* À intervalles réguliers, l'équipe réfléchit aux moyens possibles pour devenir plus efficace. Puis elle s'adapte et modifie son mode de fonctionnement en conséquence.

--

=== Expertise


// end::content[]
